export const MISC_TOGGLE_SIDEBAR = "MISC_TOGGLE_SIDEBAR";
export const MISC_SET_SIDEBAR_TOGGLED = "MISC_SET_SIDEBAR_TOGGLED";

export const AUTH_SET_USER = "AUTH_SET_USER";
export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const AUTH_SET_TOKEN_EXPIRE = "AUTH_SET_TOKEN_EXPIRE";
export const AUTH_CLEAR_ALL = "AUTH_CLEAR_ALL";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
